name: medi_call
description: Medi Call - Doctor Booking App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^5.4.0

  # Routing
  go_router: ^13.0.0

  # DI
  get_it: ^7.6.7

flutter:
  uses-material-design: true

  assets:
    - assets/
