// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdgd59uoLfZyQbQ4Sw8U4bbpLXYSFiXbc',
    appId: '1:244922269312:web:078bf0e0a0360ff48a7065',
    messagingSenderId: '244922269312',
    projectId: 'medicall-c10d6',
    authDomain: 'medicall-c10d6.firebaseapp.com',
    storageBucket: 'medicall-c10d6.firebasestorage.app',
    measurementId: 'G-5LKHRJ6YW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38jnzqVKDGTsjR-UBp4Cx2gT9VmjA-C4',
    appId: '1:244922269312:android:6b2daac75414fd608a7065',
    messagingSenderId: '244922269312',
    projectId: 'medicall-c10d6',
    storageBucket: 'medicall-c10d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLwhJPHn7T5M_DtiwvZzF67-8wF9AYsi4',
    appId: '1:244922269312:ios:d5ccfefd99e1048a8a7065',
    messagingSenderId: '244922269312',
    projectId: 'medicall-c10d6',
    storageBucket: 'medicall-c10d6.firebasestorage.app',
    iosBundleId: 'com.example.nti5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLwhJPHn7T5M_DtiwvZzF67-8wF9AYsi4',
    appId: '1:244922269312:ios:d5ccfefd99e1048a8a7065',
    messagingSenderId: '244922269312',
    projectId: 'medicall-c10d6',
    storageBucket: 'medicall-c10d6.firebasestorage.app',
    iosBundleId: 'com.example.nti5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdgd59uoLfZyQbQ4Sw8U4bbpLXYSFiXbc',
    appId: '1:244922269312:web:9f61de4803ecdb7d8a7065',
    messagingSenderId: '244922269312',
    projectId: 'medicall-c10d6',
    authDomain: 'medicall-c10d6.firebaseapp.com',
    storageBucket: 'medicall-c10d6.firebasestorage.app',
    measurementId: 'G-8X8WNMY7S0',
  );
}
